### ISSUE TITLE
Message only for certain team

### ISSUE THREAD

**Issue by crashzk** [ESK0/ServerAdvertisement#12]
Option for certain messages to be sent to the specific team.

### HOW IT WILL WORK
I would configure a message in the configuration file and have the option `team`, then I would select which team the message would go to, and only that team would see the message

Example:
```
[...]
"5"
    {
      "pt" "This message appears only for CTs"
      "type" "T"
      "team" "3"   // 2 = TR | 3 = CT
    }

"6"
    {
      "pt" "This message appears only for Ts"
      "type" "T"
      "team" "2"   // 2 = TR | 3 = CT
    }
```

**Comment by borzaka** [comment]
Can you share a use case, when an advertisement is only applicable for the T team?
For what would you use it?

**Comment by ESK0** [comment]
I dont see any real usage..

**Comment by crashzk** [comment]
I have JailBreak and TTT servers, as you know they have some specific commands for each team.

Example, JB has the commands:
- Guards have access to the !captain;
- Prisoners have access to !lr, !rebel and others.

Anyway, these servers and other specific game modes have commands that are detrimental to a certain team.

Anyway, thanks anyway.

**Comment by borzaka** [comment]
That commands should managed inside the JailBreak/TTT plugins or in their extend plugins, not in this ServerAdvertisement plugin.
