### ISSUE TITLE
Improvements in the message sending time function

### ISSUE THREAD

**Issue by crashzk** [ESK0/ServerAdvertisement#17]
Currently the plugin allows you to configure the time that messages will be sent to the server.

https://github.com/ESK0/ServerAdvertisement3/blob/f88fe5054c143fed069637886cbded7f49449c92/configs/ServerAdvertisements3.cfg#L7

It would be interesting that in each message that the user configures for the plugin to send, they have the option to put their own time, for example.

Server sends message every 30 seconds, however I configure a message that it will be sent every 480 seconds.

**Comment by Adrianilloo** [comment]
After analyzing this a bit, could be somewhat ambiguous. For instance, do you want all messages with the same interval get their own display timer and then ignore the fact that they could be printed at nearby/same time than the messages from other groups? That would be a very dynamic, beauty solution, regardless.

**Comment by crashzk** [comment]
Try to explain better, come on.

Imagine I have the following configuration:
```
"ServerAdvertisements3"
{
  "Settings"
  {
    "ServerName" "[{orange}SERVER{default}]" // Server tag
    "ServerType" "default" // Only if MySQL is 1 -> Simply divide messages to groups (e.g. 3 servers uses ServerType surf and 2 servers uses jailbreak)
    "Time" "30.0" // Time in seconds
    "Languages"  "EN" // List of languages / Keep the main language first (If player connect from Country you did not translated. He will get messages in language which is the first in list).
    "Default language" "geoip" // Value = "geoip" or "ingame"
    "Log expired messages" "0" // 1 = Enabled -> Messages are loged in Sourcemod's error log
  }
  "Welcome Message"
  {
    "Enabled" "1" // 1 = Enabled / 0 = Disabled,
    "Type" "T" // Type of message - Only T and C types are supported right now
    "en" "{orange}*************************************** \n{darkred}Welcome to this server {PLAYERNAME}! \n {lime}This server uses ServerAdvertisements3 \n Author: {bluegrey}www.steamcommunity.com/id/esk0\n{orange}***************************************"
    "Delay" "5.0" // Time in seconds after is client connected to server to show message
    "flags" "" // Client with this flag will get welcome message - Keep empty for all
  }
  "Messages"
  {
    "1"
    {
      "en" "Current map is: {CURRENTMAP} \n Players online: {PLAYERCOUNT} \n Next map: {NEXTMAP} \n Friendly fire: {mp_friendlyfire} \n Gravity: {sv_gravity}"
      "type" "T"
    }
    "2"
    {
      "en" "Message 2"
	  "time" "38.0"
      "type" "T"
    }
    "3"
    {
      "en" "Message 3"
	  "time" "120.0"
      "type" "T"
    }
  }
}
```
By default messages every 30 seconds are sent.

But message that I configure the `time` in it as in the example, it ignores the time I configured of 30 seconds and I use what is in the message itself, example of message 2 every 38 seconds it sends it.

Is that what you thought?

**Comment by Adrianilloo** [comment]
Yea, yours would be an example of a simple case.

Coding wise, that would generate three message groups with their time as an index (`"30.0"` - `"38.0"` - `"120.0"`), with each group having their own timer independent of the others. So uf you add another `38.0` seconds message, it would be included in the second group and "live together" with it (that is, it'd rotate along the timer, swapping between these two messages each `38.0` s interval, or behaving randomly only within that group per my #16 randomization support).

What I was exposing as a small inconvenience is that these groups could display at same or close times each other, for example a `30` s group and a `60` s one (a natural consequence given that the approach under consideration is to group by different times, get it now?). But as I pointed out, hopefully may not be too annoying, or admin may avoid it by shifting the intervals a bit.

**Comment by Adrianilloo** [comment]
Yea, yours would be an example of a simple case.

Coding wise, that would generate three message groups with their time as an index (`"30.0"` - `"38.0"` - `"120.0"`), with each group having their own timer independent of the others. So if you add another `38.0` seconds message, it would be included in the second group and "live together" with it (that is, it'd rotate along the timer, swapping between these two messages each `38.0` s interval, or behaving randomly only within that group per my #16 randomization support).

What I was exposing as a small inconvenience is that some groups could display at same or close times each other, for example a `30` s group and a `60` s one (a natural consequence given that the approach under consideration is to group by different intervals, get it now?). But as I pointed out, hopefully may not be too annoying, otherwise admins may avoid it by shifting the intervals a bit. Are you fine with this consequence?

Anyway, I think this feature can be very useful to allow messages with different target screen components/positioning (e.g. chat vs HUD) to overlap or simply run concurrently, increasing the players acknowledging efficiency.

**Comment by crashzk** [comment]
> Coding wise, that would generate three message groups with their time as an index (`"30.0"` - `"38.0"` - `"120.0"`), with each group having their own timer independent of the others. So if you add another `38.0` seconds message, it would be included in the second group and "live together" with it (that is, it'd rotate along the timer, swapping between these two messages each `38.0` s interval, or behaving randomly only within that group per my #16 randomization support).

I think I get it now, actually pasting the same time they can be sent at the same time. In this case I didn't think about it since I really thought about setting different times, never repeating the "global" time or that of another message.

> What I was exposing as a small inconvenience is that some groups could display at same or close times each other, for example a `30` s group and a `60` s one (a natural consequence given that the approach under consideration is to group by different intervals, get it now?). But as I pointed out, hopefully may not be too annoying, otherwise admins may avoid it by shifting the intervals a bit. Are you fine with this consequence?

For me, no problem, I believe that many will not even care about it either, I believe that many will do it like in my example, a message with `120.0` another message with `360.0` and so on.

**Comment by Adrianilloo** [comment]
@crashzk The feature is mostly ready at [this branch](https://github.com/Adrianilloo/ServerAdvertisement3/tree/time-message-groups). There is only remaining to make another full-through code revision pass (soon), as I included side enhancements and considerable refactoring, and test the feature thoroughly in-game along the plugin functioning in general.

But the branch changes should be already stable, I believe. Let me know any feedback if you're able to test it.

**Comment by Adrianilloo** [comment]
@crashzk The feature is mostly ready at [this branch](https://github.com/Adrianilloo/ServerAdvertisement3/tree/time-message-groups). There is only remaining to make another full-through code revision pass (soon), as I included side enhancements and considerable refactoring -making it error-prone-, and test the feature thoroughly in-game along the plugin functioning in general.

But the branch changes should be already stable, I believe. Let me know any feedback if you're able to test it.

Once it is fully validated I'll push the new commit at #16.

**Comment by Adrianilloo** [comment]
@crashzk The feature is mostly ready at [this branch](https://github.com/Adrianilloo/ServerAdvertisement3/tree/time-message-groups). There is only remaining to make another full-through code revision pass (soon), as I included side enhancements and considerable refactoring -making it error-prone-, and test the feature thoroughly in-game along the plugin functioning in general.

But the branch changes should be already stable, I believe. Let me know any feedback if you're able to test it.

Once it is fully validated I'll push the new commit at #16.

**Comment by crashzk** [comment]
**@Adrianilloo** first thanks, I'll be testing the version of this [branch](https://github.com/Adrianilloo/ServerAdvertisement3/tree/time-message-groups) and return with the feedback.

**[EDIT]**
Just confirm me, just add the `time` function now for the messages I want to set a separate time, right?

**Comment by crashzk** [comment]
Yes, taking advantage of this new branch of yours, I believe it would be a good idea to make some changes, namely:

- **Change the name of the include folders of the files;**

Currently everything is in the **`files`** folder but there are other plugins and even the plugin author uses these same folders and the file names are the same, but with different code.

Anyway, I believe that to correct and make something even more *"beautiful"* would be to rename the folder to the name **`ESK0`** and inside it create another folder with the name of the plugin **`ServerAdvertisements3`** and inside it put the include files of the plugin.

Something like:
```
scripting/esko/ServerAdvertisements3
```
And in the plugin change the lines:
https://github.com/Adrianilloo/ServerAdvertisement3/blob/ad5dbd21c99819af452d8f2b2821ed6b7a571318/scripting/ServerAdvertisements3.sp#L8-L9

https://github.com/Adrianilloo/ServerAdvertisement3/blob/ad5dbd21c99819af452d8f2b2821ed6b7a571318/scripting/ServerAdvertisements3.sp#L20

To leave:
```
#include "ESK0/ServerAdvertisements3/globals.sp"
#include "ESK0/ServerAdvertisements3/client.sp"

#include "ESK0/ServerAdvertisements3/misc.sp"
```
This change as I mentioned is just to make it more beautiful, aesthetic in this case.

**Comment by crashzk** [comment]
**@Adrianilloo** apparently the **`time`** function, it worked, it sent the messages in the time I configured. In this case I believe that I set times greater than the global and even then it sent faster.

What bugu was the TAG of the messages, it doesn't show anymore and neither does the line break function.

I made a video showing how messages are being sent,

https://drive.google.com/file/d/1QlkNI60eiGYbzJKPJd2u5QK0aFQ1fFNs/view?usp=sharing

As you can see in the video, the welcome message is not skipping a line and apparently lowered the character limit per message, and all messages do not show the TAG I configured.

Attached is the configuration I'm using.

[ServerAdvertisement3-time-message-groups.zip](https://github.com/ESK0/ServerAdvertisement3/files/8499172/ServerAdvertisement3-time-message-groups.zip)

**Comment by Adrianilloo** [comment]
Thank you @crashzk. I'll revise the issues when I'm free. Already realized I had inadvertedly lost the tag feature from refactoring the printing functionality into a single function, as there was mostly duplicated code between the welcome and post-messages handling.

Regarding your file restructure, I'm not particularly in favour of that pattern, which I haven't seen a lot either. You can (and should) have the plugin sources in a separate folder in case it creates name conflicts with unrelated files. What's true is that the `.sp` extension being used for include-only, non self-compilable files is a poor practice. I'll sort it too, now that you pointed out.

**Comment by Adrianilloo** [comment]
@crashzk You may try again downloading [my updated branch](https://github.com/Adrianilloo/ServerAdvertisement3/tree/time-message-groups). I've fixed the line break support and tested with your config.

**Comment by crashzk** [comment]
**@Adrianilloo**tested, TAG, and the new `time` option apparently working, but I noticed some BUGS yet.

Welcome message, receives the TAG, previous versions of the plugin she did not receive, it is better in this case, since whenever the plugin skips a line, it automatically adds a TAG.

![20220417194339_1](https://user-images.githubusercontent.com/32937653/163735567-254f32a4-af33-43a8-a7fa-1f37d92d1a63.jpg)

Anyway, I believe that the welcome message doesn't need a TAG, only the messages that you configure later in the file itself.

**Comment by Adrianilloo** [comment]
@crashzk Would you be fine overriding the tag with an empty one in whe `"Welcome Message"` section? Just configure it like this:

```
"Welcome Message"
{
	"tag"	""
	"en"	"{deepskyblue}Welcome to the server, {green}{PLAYERNAME}{deepskyblue}! Have fun"
	"es"	"{deepskyblue}¡Bienvenid@ al servidor, {green}{PLAYERNAME}{deepskyblue}! Que te diviertas"
	"delay"	"1"
}
```

This is what I'm using. This way plugin doesn't enforce one decision or the opposite, but can be configured dynamically (even when this method not being a "yes/no" setting).

**Comment by crashzk** [comment]
> @crashzk Would you be fine overriding the tag with an empty one in whe `"Welcome Message"` section? Just configure it like this:
> 
> ```
> "Welcome Message"
> {
> 	"tag"	""
> 	"en"	"{deepskyblue}Welcome to the server, {green}{PLAYERNAME}{deepskyblue}! Have fun"
> 	"es"	"{deepskyblue}¡Bienvenid@ al servidor, {green}{PLAYERNAME}{deepskyblue}! Que te diviertas"
> 	"delay"	"1"
> }
> ```
> 
> This is what I'm using. This way plugin doesn't enforce one decision or the opposite, but can be configured dynamically (even when this method not being a "yes/no" setting).

Perfect, I'll try that.

Regarding the issue of skipping a line and automatically including the TAG. Would it be possible to remove this feature?

In this case, I would like to configure some messages with this line break, but I do not want the continuation of the message to be with the TAG I configured. TAG only shows at the beginning of the message and after skipping a line don't show it again.

Would that be possible?

**Comment by Adrianilloo** [comment]
@crashzk Yes, I also thought about this, which can be an inconvenience depending on each content and/or vision. I'll make some new setting for it, defaulting to allow multi-line tags to preserve original intent.

EDIT: A better solution could be a new replaceable token, like "{TAG}" which can be embed in the messages so that user adds it where and how much they want. This would then be supported in any type of message. Then combining with using empty/no tag setting for your use case.

**Comment by crashzk** [comment]
> @crashzk Yes, I also thought about this, which can be an inconvenience depending on each content and/or vision. I'll make some new setting for it, defaulting to allow multi-line tags to preserve original intent.

It would be perfect.

> EDIT: A better solution could be a new replaceable token, like "{TAG}" which can be embed in the messages so that user adds it where and how much they want. This would then be supported in any type of message. Then combining with using empty/no tag setting for your use case.

I liked the option above, but I believe that this would be better for most users, as they would have full control whether or not they want to put the TAG in the message even if they skip lines.

**Comment by Adrianilloo** [comment]
@crashzk I have done these changes to the tag handling:

- Reverted to limiting `tag` setting effectiveness to post-join messages only
- Added support for the `{TAG}` variable/token in all message types (welcome/post-join, HUD element...), as commented earlier

Here's an example to realize the new behaviour:

```
"Welcome Message"
{
	"tag" "{green}[MYSERVER]"
	"en" "{TAG} {deepskyblue}Welcome to the server, {green}{PLAYERNAME}{deepskyblue}! Have fun\n{darkorange}[SaySounds] {deepskyblue}Type {green}!stop {deepskyblue}to stop the welcome music (if you have sounds enabled)"
	"es" "{TAG} {deepskyblue}¡Bienvenid@ al servidor, {green}{PLAYERNAME}{deepskyblue}! Que te diviertas\n{darkorange}[SaySounds] {deepskyblue}Escribe {green}!stop {deepskyblue}para detener la música de bienvenida (si tienes los sonidos activados)"
}
```

And if no `{TAG}` instance was present, then tag won't be printed in Welcome message anymore (as originally). You can now safely remove the empty `"tag" ""` declaration I had mentioned in relation to previous changes, if you still have it.

Compile and test changes again from [here](https://github.com/Adrianilloo/ServerAdvertisement3/tree/time-message-groups).

**Comment by crashzk** [comment]
@Adrianilloo so far all, thank you.

From what I've seen so far without bugs/errors, in any case I'll play and give you better feedback, but I believe I can already be merged into the branch [master](https://github.com/ESK0/ServerAdvertisement3/pull/16).

**Comment by crashzk** [comment]
Implemented in PR https://github.com/ESK0/ServerAdvertisement3/pull/16.
