### ISSUE TITLE
[Request] Messages in random order.

### ISSUE THREAD

**Issue by SefoNotasi** [ESK0/ServerAdvertisement#28]
Can you please make a random message feature? (like DJ Tsunami's Advertisements plugin: sm_advertisements_random — Enable/disable random advertisements. When enabled, advertisements are randomized on every map change and reload).

Very much lacking it.

**Comment by crashzk** [comment]
Have you tested this option?

```
"Random" "0" // Whether to randomize order of messages 
```

https://github.com/ESK0/ServerAdvertisement3/blob/efc44086334f9324741573d4c9b0cac80c9ef564/configs/ServerAdvertisements.cfg#L4-L11

**Comment by SefoNotasi** [comment]
Thank you, I tried it, it work like a charm.
In the description of the plugin was not this command and I thought that this function is not in it.
