### ISSUE TITLE
Invalid Cookie Handle

### ISSUE THREAD

**Issue by jonteohr** [ESK0/ServerAdvertisement#4]
I get this error each time the plugin is supposed to print a message:
http://imgur.com/IU5K4Qg

**Comment by 2called-chaos** [comment]
I think he tested something and reverted it but not properly... I fixed it in a fork:

https://github.com/2called-chaos/ServerAdvertisement/commit/acb01afc1abcd4ce1ba9036b20aa05f8815ac691

Download smx/sp https://github.com/2called-chaos/ServerAdvertisement

**Comment by ESK0** [comment]
Fixed in new version.
