### ISSUE TITLE
Config for 'Server Advertisement' not found!

### ISSUE THREAD

**Issue by szogi1910** [ESK0/ServerAdvertisement#5]
L 10/27/2016 - 19:08:14: [SM] Exception reported: Config for 'Server Advertisement' not found!
L 10/27/2016 - 19:08:14: [SM] Blaming: ServerAdvertisement.smx
L 10/27/2016 - 19:08:14: [SM] Call stack trace:
L 10/27/2016 - 19:08:14: [SM] [0] SetFailState
L 10/27/2016 - 19:08:14: [SM] [1] Line 194, ServerAdvertisement.sp::LoadConfig
L 10/27/2016 - 19:08:14: [SM] [2] Line 43, ServerAdvertisement.sp::OnPluginStart
L 10/27/2016 - 19:08:14: [SM] Unable to load plugin "ServerAdvertisement.smx": Error detected in plugin startup (see error logs)

That's the problem that I have uploaded the file

https://zapodaj.net/images/1d083e2cffec7.png

**Comment by ESK0** [comment]
Download new version
