### ISSUE TITLE
ArrayList

### ISSUE THREAD

**Issue by eminem0091** [ESK0/ServerAdvertisement#9]
L 02/08/2019 - 22:29:05: [SM] Exception reported: Invalid Handle 3be0327 (error: 1)
L 02/08/2019 - 22:29:05: [SM] Blaming: ServerAdvertisements3.smx
L 02/08/2019 - 22:29:05: [SM] Call stack trace:
L 02/08/2019 - 22:29:05: [SM]   [0] ArrayList.Get
L 02/08/2019 - 22:29:05: [SM]   [1] Line 470, D:\Desktop\unicorn\scripting\ServerAdvertisements3.sp::LoadMessages
L 02/08/2019 - 22:29:05: [SM]   [2] Line 375, D:\Desktop\unicorn\scripting\ServerAdvertisements3.sp::LoadConfig
L 02/08/2019 - 22:29:05: [SM]   [3] Line 57, D:\Desktop\unicorn\scripting\ServerAdvertisements3.sp::OnMapStart

**Comment by ESK0** [comment]
Should be fixed
